[files]
# Skip these files in typo checks
extend-exclude = [
    "agents/*.md",
    "csrc/xpu_ops.h",
    "csrc/xpu_ops.cpp",
    "csrc/xpu_kernels.h",
    "csrc/xpu_kernels.cpp"
]

[default]
extend-ignore-re = [
    "@Ther-nul",  # valid Github user
    "UE4M3",  # unsigned E4M3 floating point format (NVFP4 block scale type)
    "ue4m3",  # unsigned E4M3 lowercase
    "IST[ -]",  # IST Austria / IST-DASLab (Institute of Science and Technology)
    "ist-",  # ist-daslab lowercase in anchor links
]
extend-ignore-identifiers-re = [
    ".*arange.*",
    ".*ARANGE.*",
]

[type.py.extend-words]
"BA" = "BA"  # used as a commented-out variable in tests

[type.cuda.extend-words]
"subtile" = "subtile"
"subtiles" = "subtiles"
"transation" = "transation"  # TODO: is this transition, transaction, translation..?
"ue" = "ue"  # UE4M3: unsigned E4M3 floating point format (NVFP4 block scale type)
